# Initialize the inverse (inv) to NULL and defines the functions: set(), get(),
# setinverse(), and getinverse(). set() assigns the input matrix to x and get()
# simply retrieves the value of x. setinverse() assigns the input inverse to inv
# and getinverse() retrieves its value. A list is then created and returned with
# the four previous functions in it, which can be used to set and access the 
# matrix and its inverse

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


# Takes the function list generated by makeCacheMatrix as input and accesses the
# inverse if it has already been cached. If the inverse is NULL, it gets the
# matrix from makeCacheMatrix, solves for its inverse, then caches the inverse for 
# later use, and finally returns the inverse.

cacheSolve <- function(x, ...) {
        inv <- x$getinverse()
        if(!is.null(inv)) { 
            return(inv)
        }
        data <- x$get()
        inv <- solve(data)
        x$setinverse(inv)
        inv
}
